baseURL = 'https://agents4j.github.io/'
languageCode = 'en-us'
title = 'Agents4J: An agent framework for Java'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[caches]
[caches.images]
dir = ':cacheDir/images'
